_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 7a2bbac3-026b-478a-9ab4-137d2a88ef5f
name: 'Elektronski dnevnik'
mail: contact@elektronski-dnevnik.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
